server:
  port: 8082

spring:
  datasource:
    url: 127.0.0.1:3306/userdata
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  redis:
    jedis:
      pool:
        min-idle: 2
        max-idle: 8
    port: 6379



